name: Deploy to Production

on:
    push:
        branches:
            - develop

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Tailscale
              run: |
                  curl -fsSL https://tailscale.com/install.sh | sh

            - name: Connect to Tailscale Network
              env:
                  TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
                  TAILSCALE_NETWORK_ID: ${{ secrets.TAILSCALE_NETWORK_ID }}
              run: |
                  sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes --hostname=$GITHUB_RUN_ID

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: SSH into Azure VM
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.STAGING_APP_IP }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd zenitha-api
                      git pull https://AbdRaqeeb:${{ secrets.PROJECT_TOKEN }}@github.com/PathfinderHQ/zenitha-api develop
                      yarn build
                      pm2 reload zenitha --watch --update-env
