name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: 18.16.0

            - name: npm install, build, and test
              run: |
                  npm install --include=dev
                  npm run build
                  cp package.json ./dist/package.json
                  cd dist
                  zip -q -r ${{ env.APP_NAME }}.zip . -x '*.git*'
                  mv ${{ env.APP_NAME }}.zip ../

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: node-app
                  path: ${{ env.APP_NAME }}.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: node-app

            - name: Publish to Azure App Service
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ secrets.AZURE_APP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.APP_NAME }}.zip
