name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Tailscale
              run: |
                  curl -fsSL https://tailscale.com/install.sh | sh

            - name: Connect to Tailscale Network
              env:
                  TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
                  TAILSCALE_NETWORK_ID: ${{ secrets.TAILSCALE_NETWORK_ID }}
              run: |
                  sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --accept-routes --hostname=$GITHUB_RUN_ID

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.2
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Azure VM
              run: |
                  ssh ${{ secrets.USER }}@${{ secrets.APP_IP }} "cd zenitha-api && git pull origin main && yarn install && yarn build && pm2 reload ${{ secrets.APP_NAME }}"
